# Generated by Django 5.1.5 on 2025-02-10 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_category_item_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='users_read',
            field=models.ManyToManyField(blank=True, related_name='read_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
