# Generated by Django 5.1.5 on 2025-02-11 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_users_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='readlisted_by',
            field=models.ManyToManyField(blank=True, related_name='readlist_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
