# Generated by Django 5.1.5 on 2025-02-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_readlisted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
