# Generated by Django 5.1.5 on 2025-02-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_user_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_review',
            old_name='book',
            new_name='item',
        ),
    ]
