# Generated by Django 5.1.4 on 2026-01-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_rename_book_user_review_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='google_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
